import java.util.List;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.Select;
import org.testng.reporters.JqReporter;

import com.gargoylesoftware.htmlunit.javascript.host.file.File;
import com.google.common.base.Function;

public class SeleniumTest {

	public static void main(String[] args) {
		System.setProperty("webdriver.chrome.driver", "C:/Karthik/Selenium/chromedriver.exe");
		ChromeOptions options = new ChromeOptions();
		
		//locate the fluidtester.crx
		options.addExtensions(new java.io.File("C:/Users/kavi/Documents/GitHub/fluidtester/fluidtester.crx"));
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability(ChromeOptions.CAPABILITY, options);
		ChromeDriver chromeDriver = new ChromeDriver(capabilities);
		
		//replace fnbbgpchloaiaocgopjaimnecfbbolhh with the unique id generated by the chrome 
		chromeDriver.get("chrome-extension://fnbbgpchloaiaocgopjaimnecfbbolhh/index.html");
		WebElement link = chromeDriver.findElement(By.id("txt"));
		
		chromeDriver.manage().window().maximize();
		chromeDriver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		link.clear();
	
		link.sendKeys("http://www.faz.net/");
		chromeDriver.findElement(By.className("input-group-btn")).click();
		chromeDriver.manage().timeouts().implicitlyWait(4, TimeUnit.SECONDS);
		
		Dimension iframe = chromeDriver.findElement(By.id("display")).getSize();
		
		 WebElement insideIfr = chromeDriver.findElement(By.id("display"));
		 chromeDriver.switchTo().frame(insideIfr);
		 
		 JavascriptExecutor js = (JavascriptExecutor)chromeDriver;
		 js.executeScript("document.getElementById('display')");
		 js.executeScript("window.scrollBy(2000,0)", ""); 
		 long scrollPosition = (long)js.executeScript("return window.scrollX;");
		
		 if (scrollPosition != 0){
			 System.out.println("This webpage is not responsive");
		 }
		 else{
			 System.out.println("This webpage is responsive");
		 }
		 
	}
}
